
package assignment4.ds;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CaregiverService", targetNamespace = "http://ds.Assignment4/", wsdlLocation = "http://localhost:62109/WebService/CaregiverService.asmx?WSDL")
public class CaregiverService
    extends Service
{

    private final static URL CAREGIVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException CAREGIVERSERVICE_EXCEPTION;
    private final static QName CAREGIVERSERVICE_QNAME = new QName("http://ds.Assignment4/", "CaregiverService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:62109/WebService/CaregiverService.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CAREGIVERSERVICE_WSDL_LOCATION = url;
        CAREGIVERSERVICE_EXCEPTION = e;
    }

    public CaregiverService() {
        super(__getWsdlLocation(), CAREGIVERSERVICE_QNAME);
    }

    public CaregiverService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CAREGIVERSERVICE_QNAME, features);
    }

    public CaregiverService(URL wsdlLocation) {
        super(wsdlLocation, CAREGIVERSERVICE_QNAME);
    }

    public CaregiverService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CAREGIVERSERVICE_QNAME, features);
    }

    public CaregiverService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CaregiverService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CaregiverServiceSoap
     */
    @WebEndpoint(name = "CaregiverServiceSoap")
    public CaregiverServiceSoap getCaregiverServiceSoap() {
        return super.getPort(new QName("http://ds.Assignment4/", "CaregiverServiceSoap"), CaregiverServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CaregiverServiceSoap
     */
    @WebEndpoint(name = "CaregiverServiceSoap")
    public CaregiverServiceSoap getCaregiverServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://ds.Assignment4/", "CaregiverServiceSoap"), CaregiverServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CAREGIVERSERVICE_EXCEPTION!= null) {
            throw CAREGIVERSERVICE_EXCEPTION;
        }
        return CAREGIVERSERVICE_WSDL_LOCATION;
    }

}
