
package assignment4.ds;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CaregiverServiceSoap", targetNamespace = "http://ds.Assignment4/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CaregiverServiceSoap {


    /**
     * 
     * @param caregiver
     * @return
     *     returns assignment4.ds.ArrayOfRecommendationDTO
     */
    @WebMethod(action = "http://ds.Assignment4/viewRecommendations")
    @WebResult(name = "viewRecommendationsResult", targetNamespace = "http://ds.Assignment4/")
    @RequestWrapper(localName = "viewRecommendations", targetNamespace = "http://ds.Assignment4/", className = "assignment4.ds.ViewRecommendations")
    @ResponseWrapper(localName = "viewRecommendationsResponse", targetNamespace = "http://ds.Assignment4/", className = "assignment4.ds.ViewRecommendationsResponse")
    public ArrayOfRecommendationDTO viewRecommendations(
        @WebParam(name = "caregiver", targetNamespace = "http://ds.Assignment4/")
        String caregiver);

}
