
package assignment4net.assignment4net.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CaregiverServiceService", targetNamespace = "http://service.assignment4net.Assignment4Net/", wsdlLocation = "http://net-ws-app:9113/webservices/caregiverservices?wsdl")
public class CaregiverServiceService
    extends Service
{

    private final static URL CAREGIVERSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException CAREGIVERSERVICESERVICE_EXCEPTION;
    private final static QName CAREGIVERSERVICESERVICE_QNAME = new QName("http://service.assignment4net.Assignment4Net/", "CaregiverServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://net-ws-app:9113/webservices/caregiverservices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CAREGIVERSERVICESERVICE_WSDL_LOCATION = url;
        CAREGIVERSERVICESERVICE_EXCEPTION = e;
    }

    public CaregiverServiceService() {
        super(__getWsdlLocation(), CAREGIVERSERVICESERVICE_QNAME);
    }

    public CaregiverServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CAREGIVERSERVICESERVICE_QNAME, features);
    }

    public CaregiverServiceService(URL wsdlLocation) {
        super(wsdlLocation, CAREGIVERSERVICESERVICE_QNAME);
    }

    public CaregiverServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CAREGIVERSERVICESERVICE_QNAME, features);
    }

    public CaregiverServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CaregiverServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CaregiverService
     */
    @WebEndpoint(name = "CaregiverServicePort")
    public CaregiverService getCaregiverServicePort() {
        return super.getPort(new QName("http://service.assignment4net.Assignment4Net/", "CaregiverServicePort"), CaregiverService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CaregiverService
     */
    @WebEndpoint(name = "CaregiverServicePort")
    public CaregiverService getCaregiverServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.assignment4net.Assignment4Net/", "CaregiverServicePort"), CaregiverService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CAREGIVERSERVICESERVICE_EXCEPTION!= null) {
            throw CAREGIVERSERVICESERVICE_EXCEPTION;
        }
        return CAREGIVERSERVICESERVICE_WSDL_LOCATION;
    }

}
