
package assignment4net.assignment4net.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CaregiverService", targetNamespace = "http://service.assignment4net.Assignment4Net/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CaregiverService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<assignment4net.assignment4net.service.RecommendationDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "viewRecommendations", targetNamespace = "http://service.assignment4net.Assignment4Net/", className = "assignment4net.assignment4net.service.ViewRecommendations")
    @ResponseWrapper(localName = "viewRecommendationsResponse", targetNamespace = "http://service.assignment4net.Assignment4Net/", className = "assignment4net.assignment4net.service.ViewRecommendationsResponse")
    @Action(input = "http://service.assignment4net.Assignment4Net/CaregiverService/viewRecommendationsRequest", output = "http://service.assignment4net.Assignment4Net/CaregiverService/viewRecommendationsResponse")
    public List<RecommendationDTO> viewRecommendations(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
