
package com.ds.assignment4.services;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DoctorService", targetNamespace = "http://services.Assignment4.ds.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DoctorService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "annotateActivity", targetNamespace = "http://services.Assignment4.ds.com/", className = "com.ds.assignment4.services.AnnotateActivity")
    @ResponseWrapper(localName = "annotateActivityResponse", targetNamespace = "http://services.Assignment4.ds.com/", className = "com.ds.assignment4.services.AnnotateActivityResponse")
    @Action(input = "http://services.Assignment4.ds.com/DoctorService/annotateActivityRequest", output = "http://services.Assignment4.ds.com/DoctorService/annotateActivityResponse")
    public String annotateActivity(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.ds.assignment4.services.ActivityMonitorInfoDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getActivityForPatient", targetNamespace = "http://services.Assignment4.ds.com/", className = "com.ds.assignment4.services.GetActivityForPatient")
    @ResponseWrapper(localName = "getActivityForPatientResponse", targetNamespace = "http://services.Assignment4.ds.com/", className = "com.ds.assignment4.services.GetActivityForPatientResponse")
    @Action(input = "http://services.Assignment4.ds.com/DoctorService/getActivityForPatientRequest", output = "http://services.Assignment4.ds.com/DoctorService/getActivityForPatientResponse")
    public List<ActivityMonitorInfoDTO> getActivityForPatient(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.ds.assignment4.services.ActivitiesChartDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getActivitiesChart", targetNamespace = "http://services.Assignment4.ds.com/", className = "com.ds.assignment4.services.GetActivitiesChart")
    @ResponseWrapper(localName = "getActivitiesChartResponse", targetNamespace = "http://services.Assignment4.ds.com/", className = "com.ds.assignment4.services.GetActivitiesChartResponse")
    @Action(input = "http://services.Assignment4.ds.com/DoctorService/getActivitiesChartRequest", output = "http://services.Assignment4.ds.com/DoctorService/getActivitiesChartResponse")
    public ActivitiesChartDTO getActivitiesChart(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addRecommendation", targetNamespace = "http://services.Assignment4.ds.com/", className = "com.ds.assignment4.services.AddRecommendation")
    @ResponseWrapper(localName = "addRecommendationResponse", targetNamespace = "http://services.Assignment4.ds.com/", className = "com.ds.assignment4.services.AddRecommendationResponse")
    @Action(input = "http://services.Assignment4.ds.com/DoctorService/addRecommendationRequest", output = "http://services.Assignment4.ds.com/DoctorService/addRecommendationResponse")
    public String addRecommendation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.ds.assignment4.services.MonitorPillsInfoDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMonitorForPatientAndDate", targetNamespace = "http://services.Assignment4.ds.com/", className = "com.ds.assignment4.services.GetMonitorForPatientAndDate")
    @ResponseWrapper(localName = "getMonitorForPatientAndDateResponse", targetNamespace = "http://services.Assignment4.ds.com/", className = "com.ds.assignment4.services.GetMonitorForPatientAndDateResponse")
    @Action(input = "http://services.Assignment4.ds.com/DoctorService/getMonitorForPatientAndDateRequest", output = "http://services.Assignment4.ds.com/DoctorService/getMonitorForPatientAndDateResponse")
    public List<MonitorPillsInfoDTO> getMonitorForPatientAndDate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
