
package com.ds.assignment4.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DoctorServiceService", targetNamespace = "http://services.Assignment4.ds.com/", wsdlLocation = "http://java-ws-app:9999/webservices/doctorservices?wsdl")
public class DoctorServiceService
    extends Service
{

    private final static URL DOCTORSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException DOCTORSERVICESERVICE_EXCEPTION;
    private final static QName DOCTORSERVICESERVICE_QNAME = new QName("http://services.Assignment4.ds.com/", "DoctorServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://java-ws-app:9999/webservices/doctorservices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DOCTORSERVICESERVICE_WSDL_LOCATION = url;
        DOCTORSERVICESERVICE_EXCEPTION = e;
    }

    public DoctorServiceService() {
        super(__getWsdlLocation(), DOCTORSERVICESERVICE_QNAME);
    }

    public DoctorServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DOCTORSERVICESERVICE_QNAME, features);
    }

    public DoctorServiceService(URL wsdlLocation) {
        super(wsdlLocation, DOCTORSERVICESERVICE_QNAME);
    }

    public DoctorServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DOCTORSERVICESERVICE_QNAME, features);
    }

    public DoctorServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DoctorServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DoctorService
     */
    @WebEndpoint(name = "DoctorServicePort")
    public DoctorService getDoctorServicePort() {
        return super.getPort(new QName("http://services.Assignment4.ds.com/", "DoctorServicePort"), DoctorService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DoctorService
     */
    @WebEndpoint(name = "DoctorServicePort")
    public DoctorService getDoctorServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.Assignment4.ds.com/", "DoctorServicePort"), DoctorService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DOCTORSERVICESERVICE_EXCEPTION!= null) {
            throw DOCTORSERVICESERVICE_EXCEPTION;
        }
        return DOCTORSERVICESERVICE_WSDL_LOCATION;
    }

}
